### ISSUE TITLE
error: axis 3 is out of bounds for array of dimension 2

### ISSUE THREAD

**Issue by EricVibration** [Vooban/Smoothly-Blend-Image-Patches#8]
I got the en error for the function called "_windowed_subdivs". and my error codes are showed as below:
---------------------------------------------------------------------------------------------------------------------
AxisError                                 Traceback (most recent call last)
<ipython-input-15-254661f4ab08> in <module>
     11 # Use the algorithm. The `pred_func` is passed and will process all the image 8-fold by tiling small patches with overlap, called once with all those image as a batch outer dimension.
     12 # Note that model.predict(...) accepts a 4D tensor of shape (batch, x, y, nb_channels), such as a Keras model.
---> 13 predictions_smooth = predict_img_with_smooth_windowing(
     14     input_img,
     15     window_size=window_size,

~\Desktop\Python\helping somebody\Funaki san_AR2\smooth_tiled_predictions.py in predict_img_with_smooth_windowing(input_img, window_size, subdivisions, nb_classes, pred_func)
    251     for pad in tqdm(pads):
    252         # For every rotation:
--> 253         sd = _windowed_subdivs(pad, window_size, subdivisions, nb_classes, pred_func)
    254         one_padded_result = _recreate_from_subdivs(
    255             sd, window_size, subdivisions,

~\Desktop\Python\helping somebody\Funaki san_AR2\smooth_tiled_predictions.py in _windowed_subdivs(padded_img, window_size, subdivisions, nb_classes, pred_func)
    163         patches_resolution_along_X == patches_resolution_along_Y == window_size
    164     """
--> 165     WINDOW_SPLINE_2D = _window_2D(window_size=window_size, power=2)
    166 
    167     step = int(window_size/subdivisions)

~\Desktop\Python\helping somebody\Funaki san_AR2\smooth_tiled_predictions.py in _window_2D(window_size, power)
     57     else:
     58         wind = _spline_window(window_size, power)
---> 59         **wind = np.expand_dims(np.expand_dims(wind, 3), 3)**
     60         wind = wind * wind.transpose(1, 0, 2)
     61         if PLOT_PROGRESS:

<__array_function__ internals> in expand_dims(*args, **kwargs)

C:\Anaconda3\lib\site-packages\numpy\lib\shape_base.py in expand_dims(a, axis)
    595 
    596     out_ndim = len(axis) + a.ndim
--> 597     axis = normalize_axis_tuple(axis, out_ndim)
    598 
    599     shape_it = iter(a.shape)

C:\Anaconda3\lib\site-packages\numpy\core\numeric.py in normalize_axis_tuple(axis, ndim, argname, allow_duplicate)
   1383             pass
   1384     # Going via an iterator directly is slower than via list comprehension.
-> 1385     axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
   1386     if not allow_duplicate and len(set(axis)) != len(axis):
   1387         if argname:

C:\Anaconda3\lib\site-packages\numpy\core\numeric.py in <listcomp>(.0)
   1383             pass
   1384     # Going via an iterator directly is slower than via list comprehension.
-> 1385     axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
   1386     if not allow_duplicate and len(set(axis)) != len(axis):
   1387         if argname:

AxisError: axis 3 is out of bounds for array of dimension 2
--------------------------------------------------------------------------------------------------------------------------
Is it due to the problems of the version of numpy?

Sincerely

**Comment by agnaranjo** [comment]
I fixed this replacing that lines with:
```
        wind =np.expand_dims(wind, 1)
        wind = wind * wind.transpose()
        wind = np.stack((wind, wind, wind), axis=-1)
```

**Comment by gagolucasm** [comment]
@agnaranjo could you provide more details?

**Comment by margilc** [comment]
For me the fix provided by sreeni (https://www.youtube.com/watch?v=HrGn4uFrMOM) works best:
replace np.expand_dims(np.expand_dims(wind, 3), 3)
with  np.expand_dims(np.expand_dims(wind, 1), 1)
(in addition to the i/j x/y typo mentioned already by others)

**Comment by EricVibration** [comment]
Thank you for your detailed information. 
As the problem has been solved, I'd like to close this issue.
